version: '3.5'

services:
  agency:
    image: ${DOCKER_IMG_CACHED_AGENCY}
    container_name: agency
    environment:
      - LOG_JSON_TO_CONSOLE=false
      - LOG_LEVEL=info
      - SERVER_PORT=8080
      - SERVER_MAX_REQUEST_SIZE_KB=300

      - PG_WALLET_MAX_CONNECTIONS=90
      - PG_WALLET_CONNECTION_TIMEOUT_MINS=30

      - AGENCY_WALLET_NAME=vcxagency-node-ea
      - AGENCY_DID=VsKV7grR1BUE29mG2Fm2kX
      - AGENCY_SEED_SECRET=0000000000000000000000000Forward
      - AGENCY_WALLET_KEY_SECRET=98765432109876543210

      - AGENCY_TYPE=enterprise

      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ACCOUNT=root
      - MYSQL_PASSWORD_SECRET=mysecretpassword
      - MYSQL_DATABASE_APPLICATION=agency_application
      - MYSQL_DATABASE_WALLET=agency_wallets
      - MYSQL_DATABASE_WALLET_CONNECTION_LIMIT=50

      - SERVER_ENABLE_TLS=false
    network_mode: "host"
    command: ["sh", "-c", "npm run dev:schema:migrate:all && npm run serve"]
