#
# SPDX-License-Identifier: CC-BY-4.0
#

repository:
  name: aries-vcx
  description: aries-vcx
  homepage: https://wiki.hyperledger.org/display/aries
  default_branch: master 
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
