[package]
name = "indy-api-types"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
futures = { version = "0.3", default-features = false, features = ["std"] }
log = { version = "0.4.17", features = ["std"] }
libc = "0.2.148"
serde = "1.0.99"
serde_json = "1.0.40"
serde_derive = "1.0.99"
zeroize = "1.3.0"
aes = "0.8.3"
openssl = { version = "0.10" }
bs58 = "0.5.0"
sqlx = { version = "0.5.8", git = "https://github.com/jovfer/sqlx", branch = "feature/json_no_preserve_order_v5", features = [ "sqlite", "mysql", "json_no_preserve_order", "runtime-tokio-rustls" ] }
ursa = "0.3.7"