[package]
name = "indy-api-types"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["casting_errors"]
casting_errors = [ "openssl", "rust-base58", "zmq", "ursa", "sqlx"]
rust-base58 = ["bs58"]

[dependencies]
failure = "0.1.8"
futures = { version = "0.3", default-features = false }
log = { version = "0.4.17", features = ["std"] }
libc = "0.2.114"
openssl = {version = "0.10", optional = true}
bs58 = {version = "0.4.0", optional = true}
serde = "1.0.99"
serde_json = "1.0.40"
serde_derive = "1.0.99"
sqlx = { version = "0.6.2", features = [ "sqlite" ], optional = true  }
zeroize = "~1.3.0"
zmq = {version = "0.9.1", optional = true}
ursa = { version = "0.3.7", optional = true}
aes = "0.7.4"
