[package]
name = "mediator"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client"]
client = []

[dependencies]
anyhow.workspace = true
aries_vcx = { path = "../../aries_vcx" }
aries_vcx_wallet = { path = "../../aries_vcx_wallet", features = [
    "askar_wallet",
] }
async-trait.workspace = true
axum.workspace = true
diddoc_legacy = { path = "../../misc/legacy/diddoc_legacy" }
dotenvy.workspace = true
env_logger.workspace = true
futures.workspace = true
log.workspace = true
messages = { path = "../../messages" }
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["mysql"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tower-http = { workspace = true, features = ["catch-panic"] }
url.workspace = true
uuid.workspace = true
test_utils = { path = "../../misc/test_utils" }
base64.workspace = true

[dev-dependencies]
chrono.workspace = true
