[package]
name = "did_key"
version = "0.1.0"
edition = "2021"

[dependencies]
public_key = { path = "../../public_key" }
did_parser_nom = { path = "../../did_parser_nom" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
