[package]
name = "did_peer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
did_parser = { path = "../../did_parser" }
did_doc = { path = "../../did_doc" }
did_resolver = { path = "../../did_resolver" }
public_key = { path = "../../public_key" }
thiserror = "1.0.40"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
async-trait = "0.1.68"
base64 = "0.21.2"
bs58 = "0.5.0"
multibase = "0.9.1"
unsigned-varint = "0.7.1"
once_cell = "1.18.0"
sha256 = "1.1.4"
display_as_json = { path = "../../../misc/display_as_json" }

[dev-dependencies]
tokio = { version = "1.27.0", default-features = false, features = ["macros", "rt"] }
pretty_assertions = "1.4.0"
