[package]

name = "libvcx"
version = "0.42.0"
authors = ["Absa Group Limited", "Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
publish = false
description = "Absa's fork of HL LibVCX"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "vcx"
path = "src/lib.rs"
crate-type = ["staticlib","rlib", "cdylib"]

[features]
test_utils = []
pool_tests = ["test_utils", "tokio/rt", "tokio/macros"]
agency_tests = ["test_utils", "tokio/rt", "tokio/macros"]
general_test = ["test_utils", "tokio/rt", "tokio/macros"]
to_restore = []
fatal_warnings = []

[dependencies]
env_logger = "0.9.0"
log = "0.4.16"
chrono = "0.4.19"
time = "0.1.36"
lazy_static = "1.3"
libc = "=0.2.114"
rand = "0.7.3"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
rmp-serde = "0.13.7"
base64 = "0.8.0"
openssl = { version = "0.10.35", features = ["vendored"] }
futures = "0.3.15"
tokio = { version = "1.15.0", features = ["rt-multi-thread"] }
uuid = {version = "0.7.1", default-features = false, features = ["v4"]}
failure = "0.1.6"
aries_vcx = { path = "../aries_vcx" }
async-std = "1.10.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.5"

[build-dependencies]
serde = "1.0"
toml = "0.4"
serde_json = "1.0"
serde_derive = "1.0"
aries_vcx = { path = "../aries_vcx", features = ["test_utils"] }
