[package]

name = "aries-vcx"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
test_utils = [ "messages/test_utils" ]
pool_tests = [ "test_utils" ]
agency_pool_tests = ["test_utils" ]
general_test = ["test_utils", "messages/general_test" ]
fatal_warnings = []
warnlog_fetched_messages = []
mysql_test = ["test_utils", "sqlx" ]
modular_deps = ["test_utils", "tokio/rt", "tokio/macros"]

[dependencies]
async-trait = "0.1.53"
env_logger = "0.9.0"
log = "0.4.16"
chrono = "0.4.19"
time = "0.1.44"
lazy_static = "1.3"
libc = "=0.2.114"
rand = "0.7.3"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
regex = "1.1.0"
rust-base58 = "0.0.4"
base64 = "0.10"
openssl = { version = "0.10.35" }
num-traits = "0.2.0"
vdrtoolsrs = { git = "https://gitlab.com/left-arm/vdr-tools.git", rev = "aa446cb8d" }
vdrtools-sys = { git = "https://gitlab.com/left-arm/vdr-tools.git", rev = "aa446cb8d" }
# indy alternatives ----
indy-vdr = "0.3.4"
indy-credx = { git = "https://github.com/anonyome/indy-shared-rs.git", rev = "7342bc624d23ece8845d1a701cd2cdc9cd401bb0" }
# ----------------------

futures = "0.3.15"
libloading = "0.5.0"
uuid = { version = "0.8", default-features = false, features = ["v4"]}
failure = "0.1.6"
strum = "0.16.0"
strum_macros = "0.16.0"
agency_client = { path = "../agency_client" }
sqlx = { optional = true, version = "0.5", features = [ "migrate", "mysql", "runtime-async-std-native-tls" ] }
derive_builder = "0.10.2"
tokio = { version = "1.15.0" }
messages = { path  = "../messages" }
zmq = { version = "0.9.2" }

[dev-dependencies]
reqwest = "0.11.12"
tokio = { version = "1.15", features = [ "rt", "macros" ] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.5"
