[package]

name = "aries-vcx"
version = "0.25.0"
authors = ["Absa Group Limited", "Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
publish = false
license = "Apache-2.0"
edition = "2018"

[lib]
name = "aries_vcx"
path = "src/lib.rs"

[features]
test_utils = []
pool_tests = ["test_utils"]
agency_pool_tests = ["test_utils"]
agency_v2 = ["test_utils"]
general_test = ["test_utils"]
fatal_warnings = []
warnlog_fetched_messages = []
plugin_test = ["test_utils"]

[dependencies]
env_logger = "0.5.10"
log = "0.4"
chrono = "0.4"
time = "0.1.36"
lazy_static = "1.3"
libc = "=0.2.66"
rand = "0.7.3"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
url = "1.5.1"
regex = "1.1.0"
rust-base58 = "0.0.4"
rmp-serde = "0.13.7"
base64 = "0.8.0"
openssl = { version = "0.10.35", features = ["vendored"] }
num-traits = "0.2.0"
indy = "1.16.0-post-59"
indy-sys = "1.16.0-post-59"
futures = "0.3.15"
libloading = "0.5.0"
uuid = {version = "0.7.1", default-features = false, features = ["v4"]}
failure = "0.1.6"
strum = "0.16.0"
strum_macros = "0.16.0"
agency_client = { version = "0.1.0", path = "../agency_client" }
derive_builder = "0.10.2"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.5"
