[package]
name = "messages"
version = "0.1.0"
edition = "2021"

[features]
test_utils = []
general_test = ["test_utils", "tokio/rt", "tokio/macros"]

[dependencies]
log = "0.4.16"
chrono = "0.4.19"
time = "0.1.36"
rand = "0.7.3"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
url = "1.5.1"
regex = "1.1.0"
rust-base58 = "0.0.4"
base64 = "0.8.0"
num-traits = "0.2.0"
vdrtools = { git = "https://gitlab.com/mirgee/vdr-tools.git", rev = "c1390f91bc152ef31a7ead73c1c3fe286cc9cc0c" }
uuid = {version = "0.8", default-features = false, features = ["v4"]}
failure = "0.1.6"
strum = "0.16.0"
strum_macros = "0.16.0"
derive_builder = "0.10.2"
tokio = { version = "1.15.0" }

[dev-dependencies]
env_logger = "0.9.0"
lazy_static = "1.3"
