[package]
name = "aries-vcx-agent"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = "1.0.145"
test_utils = { path = "../../../tools/test_utils", features = ["credx"] }
aries-vcx = { path = "../../../aries_vcx" }
aries_vcx_core = { path = "../../../aries_vcx_core", features = ["credx", "vdrtools_wallet"] }
async-trait = "0.1.64"
derive_builder = "0.11.2"
serde_json = "1.0.85"
log = "0.4.17"
uuid = "1.2.1"
thiserror = "1.0.37"
url = { version = "2.3.1", features = ["serde"] }
