[package]
name = "did_resolver_registry"
version = "0.1.0"
edition = "2021"

[dependencies]
did_resolver = { path = "../did_resolver" }
serde_json = "1.0.103"
serde = "1.0.174"
async-trait = "0.1.72"

[dev-dependencies]
tokio = { version = "1.38.0", default-features = false, features = ["macros", "rt"] }
mockall = "0.13.0"
async-trait = "0.1.68"
