[package]
name = "agency_client"
version = "0.1.0"
authors = ["Miroslav Kovar <miroslavkovar@protonmail.com>"]
edition = "2018"

[features]
test_utils = []
general_test = ["test_utils"]
to_restore = []

[dependencies]
env_logger = "0.5.10"
log = "0.4"
lazy_static = "1.3"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
reqwest = { version = "0.9.5" }
regex = "1.1.0"
rmp-serde = "0.13.7"
rust-base58 = "0.0.4"
indy = { git = "https://gitlab.com/evernym/verity/vdr-tools.git", rev = "59e1ecc21c9a067" }
futures = "0.1.23"
url = "1.5.1"
failure = "0.1.6"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.5"
