[package]
name = "aries-vcx-cli"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
actix-web = "4.2.1"
anyhow = "1.0.66"
aries-vcx-agent = { path = "../aries-vcx-agent" }
clap = { version = "4.0.29", features = ["cargo", "derive"] }
config = "0.13.3"
env_logger = "0.10.0"
inquire = "0.5.2"
log = "0.4.17"
rand = "0.8.5"
reqwest = { version = "0.11.13", features = ["json", "multipart", "blocking"] }
serde = "1.0.148"
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["macros"] }
