[package]
name = "did_resolver"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
did_parser_nom = { path = "../did_parser_nom" }
did_doc = { path = "../did_doc" }
async-trait = "0.1.68"
chrono = { version = "0.4.24", default-features = false, features = ["serde"] }
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
serde_json = "1.0.103"
typed-builder = "0.19.1"
