[package]
name = "did_resolver"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
did_parser_nom = { path = "../did_parser_nom" }
did_doc = { path = "../did_doc" }
async-trait.workspace = true
chrono = { workspace = true, default-features = false, features = ["serde"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json.workspace = true
typed-builder.workspace = true
