[package]
name = "indy-utils"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["base64_rust_base64", "ed25519_sign_sodium", "ed25519_box_sodium", "sealedbox_sodium", "base64_rust_base64", "xsalsa20_sodium", "chacha20poly1305_ietf_sodium", "hash_openssl", "pwhash_argon2i13_sodium", "hmacsha256_sodium", "randombytes_sodium"]
base64_rust_base64 = []
ed25519_sign_sodium = []
ed25519_box_sodium = []
sealedbox_sodium = []
xsalsa20_sodium = []
chacha20poly1305_ietf_sodium = []
pwhash_argon2i13_sodium = []
hmacsha256_sodium = []
hash_openssl = []
randombytes_sodium = []

[dependencies]
base64 = {version = "0.21"}
dirs = "5"
failure = "0.1"
indy-api-types = { path = "../indy-api-types" }
lazy_static = "1"
libc = "0.2"
log = "0.4"
openssl = { version = "0.10" }
serde = "1"
serde_json = "1"
serde_derive = "1"
sodiumoxide = {version = "0.2.7"} # touching this makes things go boom
zeroize = "1"

[dev-dependencies]
rmp-serde = "1"
rand = "0.8"
